### ISSUE TITLE
RFE - integrate with dnf

### ISSUE THREAD

**Issue by ignatenkobrain** [xsuchy/rpmconf#16]
I think would be good if we will have automatically running rpmconf when updating packages in dnf.

Because rpmconf now written on python we can easily write some code and write plugin for dnf which will handle transactions

**Comment by xsuchy** [comment]
Good work. I like it. However please preserve rpmconf-base owning just that one directory. I have some plans for that.

**Comment by ignatenkobrain** [comment]
For what? Plugins?

On Wed, Jan 7, 2015 at 4:07 AM, Miroslav Suchý <notifications@github.com>
wrote:

> Good work. I like it. However please preserve rpmconf-base owning just
> that one directory. I have some plans for that.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xsuchy/rpmconf/issues/16#issuecomment-68963543>.
>



-- 
-Igor Gnatenko

**Comment by xsuchy** [comment]
> For what? Plugins?

for framework, which allows update package data. e.g. upgrade db schema. I have student who is working on that as his bachelor thesis.

**Comment by ignatenkobrain** [comment]
I've sent pull request with this directory

On Thu, Jan 8, 2015 at 10:42 AM, Miroslav Suchý <notifications@github.com>
wrote:

> For what? Plugins?
>
> for framework, which allows update package data. e.g. upgrade db schema. I
> have student who is working on that as his bachelor thesis.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xsuchy/rpmconf/issues/16#issuecomment-69146024>.
>



-- 
-Igor Gnatenko
