### ISSUE TITLE
rpmconf has issues with unicode

### ISSUE THREAD

**Issue by XRevan86** [xsuchy/rpmconf#26]
As reported in Novell Bugzilla: [#929434](https://bugzilla.novell.com/show_bug.cgi?id=929434):
```
# rpmconf -d -a
Traceback (most recent call last):
  File "/usr/sbin/rpmconf", line 63, in <module>
    main()
  File "/usr/sbin/rpmconf", line 60, in main
    rconf.run()
  File "/usr/lib/python3.4/site-packages/rpmconf/rpmconf.py", line 88, in run
    self._handle_package(pkg_hdr)
  File "/usr/lib/python3.4/site-packages/rpmconf/rpmconf.py", line 241, in _handle_package
    for conf_file in self.get_list_of_config(package):
  File "/usr/lib/python3.4/site-packages/rpmconf/rpmconf.py", line 117, in get_list_of_config
    for rpm_file in files:
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe5 in position 27: invalid continuation byte
```

**Comment by xsuchy** [comment]
Hmm I could not reproduce it on Fedora 22.
I created this rpm package with unicode config:
http://miroslav.suchy.cz/fedora/unicode-etc.rpm

On /usr/lib/python3.4/site-packages/rpmconf/rpmconf.py +117 is rpm_file set to e.g.:

 ('/etc/žufuřík', 0, 33188, 1432637817, 1, 0, 1, 1, 0, -1, 'root', 'root', 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855')

I would guess that the problem actually happen in rpm.fi object object when it try to return one item from rpm.fi object (files variable).

This is mininal reproducer:
```
import rpm
trans = rpm.TransactionSet()
tmp = trans.dbMatch("name", "copr-ping")
for pkg in tmp:
    files = rpm.fi(pkg) 
    for rpm_file in files:                                                                                                                     
      print(rpm_file)
```
On Fedora it prints:
```
 ('/etc/žufuřík', 0, 33188, 1432637817, 1, 0, 1, 1, 0, -1, 'root', 'root', 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855')
```
If this fails on SUSE, it is very likely bug in SUSE version of python-rpm or python3-rpm.
Can you please investigate it? I do not have SUSE installation.

**Comment by XRevan86** [comment]
On openSUSE Tumbleweed it prints the same.

**Comment by XRevan86** [comment]
Original issue has been closed and so does this one.
