### ISSUE TITLE
rpmconf crashes with broken symlink

### ISSUE THREAD

**Issue by boris-penev** [xsuchy/rpmconf#28]
Error message:

```
Traceback (most recent call last):
  File "/sbin/rpmconf", line 63, in <module>
    main()
  File "/sbin/rpmconf", line 60, in main
    rconf.run()
  File "/usr/lib/python3.4/site-packages/rpmconf/rpmconf.py", line 90, in run
    self._handle_package(pkg_hdr)
  File "/usr/lib/python3.4/site-packages/rpmconf/rpmconf.py", line 264, in _handle_package
    tmp.format(conf_file, "rpmnew"))
  File "/usr/lib/python3.4/site-packages/rpmconf/rpmconf.py", line 273, in _handle_rpmnew
    if filecmp.cmp(conf_file, other_file):
  File "/usr/lib64/python3.4/filecmp.py", line 51, in cmp
    s1 = _sig(os.stat(f1))
FileNotFoundError: [Errno 2] No such file or directory: '/etc/mock/default.cfg'
```

Description of problem:
I upgraded Fedora 20 to 21 and then to 22. I ran `rpmconf -a` to manage the update configurations. When the mock package was reached, rpmconf crashed with FileNotFoundError exception. When I investigated further, it turned out the change was not a file content but a symlink.

```sh
$ ls -l /etc/mock/default.cfg*
/etc/mock/default.cfg -> fedora-20-x86_64.cfg (missing)
/etc/mock/default.cfg.rpmnew -> fedora-22-x86_64.cfg
```

Maybe rpmconf is not checking if the symlink is broken. Running `man rpmconf | grep link` did not produce any output. Apparently this symlink has been a problem for rpmconf in the past, as evidenced in #11.

Expected results: rpmconf should be able to diff the symlink instead of dereferencing it, at least in case it is broken, allowing you to keep the right symlink. If not, it should at least gracefully handle it - tell you that your symlink is broken and you should fix it yourself.

Version-Release number of selected component: 1.0.90 and master

Regarding the version, while filing the bug, I built against git master head and tested that it is still reproducible there.

**Comment by xsuchy** [comment]
This should be fixed  by fef30241c906ebf95d4443f83558eae13da4b21b
