### ISSUE TITLE
[rfe] provide option to use vimdiff

### ISSUE THREAD

**Issue by genodeftest** [xsuchy/rpmconf#29]
Quite often I want to keep some parts of my old configuration, but new config files have new interesting options. In these cases I run vimdiff on those files anyway. Would you mind adding an option to run vimdiff (as there is to run diff) on a pair of files? Ideally the current config file would be on the left side and the .rpmnew and .rpmsave files on the right.

**Comment by xsuchy** [comment]
It is already there:
```
  rpmconf -fvimdiff 
```
It is run when you choose (M)erge option on specific file.

From man page:
```
       -f<type>, --frontend=<type>
              Define  which  frontend  should  be used for merging. Valid options are: vimdiff, gvimdiff, diffuse, kdiff3, meld and
              env. When set to env, the command to use is taken from the environment variable $MERGE. The default is env.
```

**Comment by genodeftest** [comment]
Oh, sorry for the noise.
