### ISSUE TITLE
sdiff support

### ISSUE THREAD

**Issue by mikccc** [xsuchy/rpmconf#35]
Please consider adding support for sdiff.

> The sdiff command merges two files and interactively outputs the results. Its arguments are as follows:
>
>`sdiff -o outfile options… from-file to-file`
>This merges from-file with to-file, with output to outfile. If from-file is a directory and to-file is not, sdiff compares the file in from-file whose file name is that of to-file, and vice versa. from-file and to-file may not both be directories.
>
>sdiff options begin with ‘-’, so normally from-file and to-file may not begin with ‘-’. However, -- as an argument by itself treats the remaining arguments as file names even if they begin with ‘-’. You may not use - as an input file.
>
>sdiff without --output (-o) produces a side-by-side difference. This usage is obsolete; use the --side-by-side (-y) option of diff instead.
>
>An exit status of 0 means no differences were found, 1 means some differences were found, and 2 means trouble.

https://www.gnu.org/software/diffutils/manual/diffutils.html#Invoking-sdiff

**Comment by xsuchy** [comment]
Hmm, I tried to start on this, but contradictory to man page I am getting exit code 1 when error (e.g. ed command failed) and 2 when some differences found (v command).

**Comment by gissf1** [comment]
etc-update, which is a tool for Gentoo that performs a similar function to rpmconf, uses sdiff by default.  Perhaps looking at their code can give you some insight?  See: https://github.com/gentoo/portage/blob/master/bin/etc-update

**Comment by xsuchy** [comment]
Done in 1f3577916678c391614c8e1091645a8a1f3c8347
