### ISSUE TITLE
New option: --root

### ISSUE THREAD

**Issue by dmach** [xsuchy/rpmconf#36]
Rpmconf currently works only with the / file system.
If dnf works in an installroot, rpmconf plugin doesn't work with packages in that directory, it touches system packages.
I'm proposing to add --root option (as RPM has) to switch to that root and work in it.
Then we can fix rpmconf dnf plugin to work correctly.

**Comment by xsuchy** [comment]
Do you know what is equivalent of `rpm.TransactionSet()` to start transaction in `--root`?
