### ISSUE TITLE
Update latest version in EPEL, because current "latest" is 0.3.4 from Feb 2015

### ISSUE THREAD

**Issue by thomas-merz** [xsuchy/rpmconf#40]
I found out, that we use rpmconf from [EPEL-Repo](https://mirror.karneval.cz/pub/linux/fedora/epel/7/x86_64/Packages/r/) for RHEL7, but the latest version there is 0.3.4 from Feb 2015!!!??? :-(
As "this project is sponsored by Red Hat" I would assume that you might have some possibilities to have this package updated in EPEL?
I had a ticket with Rohan Sable, Red Hat Technical Support, who gave me the hint about you/EPEL ;-)

**Comment by xsuchy** [comment]
Yes. The reason I stopped updated rpmconf in EPEL7 is that I moved to python3 in upstream. And EPEL7 did not have python3 in past. This is no longer true as there is python3 package in EPEL7. I will check if all requirements are there now and if yes, I will build it there.

**Comment by xsuchy** [comment]
And it is done:
https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2020-1547775147
