### ISSUE TITLE
Noninteractive mode for -a

### ISSUE THREAD

**Issue by xsuchy** [xsuchy/rpmconf#41]
See https://github.com/xsuchy/rpmconf/issues/39

**Comment by xsuchy** [comment]
Ha, @thomas-merz  this has already been implemented. I just forgot about it. It is `-t` option:

```
# touch /etc/yum.repos.d/fedora.repo.rpmnew
# rpmconf -t -o fedora-repos
/etc/yum.repos.d/fedora.repo.rpmnew
# echo $?
5
# rpmconf -t -a
/etc/yum.repos.d/fedora.repo.rpmnew
# echo $?
5
```
There have been a small issue which I fixed in 936c347

**Comment by thomas-merz** [comment]
Thanks, I will have to wait and be patient until I will see a more current version than 0.3.4 in EPEL-Repo.

**Comment by xsuchy** [comment]
@thomas-merz https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2020-1547775147 two more days :)
