### ISSUE TITLE
Cannot compile on Amazon Linux 2

### ISSUE THREAD

**Issue by daniejstriata** [xsuchy/rpmconf#47]
I'm running into problems with Amazon Linux 2 as the default Python is not the same as used for Centos 7. I'll update here as I find more.

I also cannot install tito due to python on Amazon Linux 2 being on 3.7.

**Comment by xsuchy** [comment]
Yes. This is a problem. Amazon Linux includes python3.7 in amzn2-core. While EPEL7 (where rpmconf is) uses python3.4. You can install it directly from git checkout using `python3 setup.py install ` or asks Amazon to include it in e.g. amzn2-extras.

If you provide some repos for amzn2 I can add it to README, but I am afraid I will have no time to do an actual work about this.

**Comment by daniejstriata** [comment]
Whoever needs to. Install this extra to make rpmconf work:
`
yum install python3-rpm.x86_64 python3-rpm-macros.noarch`
